/*
*************** MPU_program.c ***************
*  Author : Ammar Mohamed Hraga
*  layer  : MCAL
*/

#include "std_types.h"
#include "bit_math.h"
#include "MPU_reg.h"
#include "MPU_interface.h"
#include "MPU_config.h"
#include "MPU_private.h"


void MPU_voidInit(void)
{

	
	MPU->CTRL = 0;

	MPU->RNR = 0;
	MPU->RBAR = MPU_REGION0_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION0_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION0_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION0_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION0_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION0_STATUS << MPU_RASR_ENABLE);

	MPU->RNR = 1;
	MPU->RBAR = MPU_REGION1_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION1_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION1_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION1_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION1_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION1_STATUS << MPU_RASR_ENABLE);

	MPU->RNR = 2;
	MPU->RBAR = MPU_REGION2_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION2_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION2_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION2_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION2_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION2_STATUS << MPU_RASR_ENABLE);

	MPU->RNR = 3;
	MPU->RBAR = MPU_REGION3_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION3_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION3_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION3_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION3_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION3_STATUS<< MPU_RASR_ENABLE);


	MPU->RNR = 4;
	MPU->RBAR = MPU_REGION4_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION4_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION4_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION4_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION4_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION4_STATUS << MPU_RASR_ENABLE);

	MPU->RNR = 5;
	MPU->RBAR = MPU_REGION5_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION5_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION5_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION5_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION5_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION5_STATUS << MPU_RASR_ENABLE);

	MPU->RNR = 6;
	MPU->RBAR = MPU_REGION6_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION6_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION6_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION6_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION6_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION6_STATUS << MPU_RASR_ENABLE);
				
	MPU->RNR = 7;
	MPU->RBAR = MPU_REGION7_BASE_ADDRESS;
	MPU->RASR = (MPU_REGION7_SIZE <<MPU_RASR_SIZE_SHIFT )|
				(MPU_REGION7_AP << MPU_RASR_AP_SHIFT)|
				(MPU_REGION7_XN << MPU_RASR_XN_SHIFT)|
				(MPU_REGION7_MEM_TYPE << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_REGION7_STATUS << MPU_RASR_ENABLE);



}



void MPU_voidConfigRegion(MPU_RegionConfig_t * MPU_RegionConfig )
{
	u32 Local_u32CtrlBackup = MPU->CTRL;
	MPU->CTRL = 0;
	MPU->RNR = MPU_RegionConfig->RegionNumber ;
	MPU->RBAR = MPU_RegionConfig->RegionAddress ;
	MPU->RASR = (MPU_RegionConfig->RegionSize <<MPU_RASR_SIZE_SHIFT )|
				(MPU_RegionConfig->RegionPermission << MPU_RASR_AP_SHIFT)|
				(MPU_RegionConfig->RegionXNSelect << MPU_RASR_XN_SHIFT)|
				(MPU_RegionConfig->RegionMemType << MPU_RASR_MEM_TYPE_SHIFT)|
				(MPU_RegionConfig->RegionState << MPU_RASR_ENABLE);			
	
	MPU->CTRL  =  Local_u32CtrlBackup;
}

void MPU_voidEnable(void)
{ 
	MPU->CTRL |= 1 ;
	__asm volatile ("dsb");
	__asm volatile ("isb");
}

void MPU_voidDisable(void)
{
	MPU->CTRL = 0;
}

void MemManageFault_voidEnable(void)
{
	SET_BIT(SCB_SHCSR,16);
}


void MemManageFault_voidDisable(void)
{
	CLR_BIT(SCB_SHCSR,16);
}
